version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  reviewers:
  - diamondap
  assignees:
  - diamondap
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - "> 1.35.2, < 2"
  - dependency-name: github.com/stretchr/testify
    versions:
    - 1.7.0
