language: go
sudo: required
go:
- 1.13.1
- tip
cache:
  directories:
  - "$HOME/.cache/go-build"
addons:
  apt:
    packages:
    - libmagic-dev
script: go test `go list ./... | grep -v integration`
notifications:
  slack:
    secure: cbMsw0yKDaA1t1U7Pl26E1SiSMNztttv5M0ZjNvXwMJg6k9zDKuk2OHI/Ka8jhEoR5QexOs9jYvYPj+xmA4WmKEPM2f834UvuatllICRoWVp2fpAEv1rO8xqlFbJVBDtgaLrjMA3Tc1lhmRlUEdpzEPWa9FQr5jzZxGhYfn+lRGzKplESLAmw29RiECqASuruSvcI3DTp9E4hAtGFQTZe3V7kI/X0hh9GOCSMz+83CPOCwjwlkvDYy5m2JhyyCTS1dJruVc8PbFmaYzh/pb0RU8kRdq/tcyqAszXwxDm5FFJ7VWLGMIkxd3q9iuXBaR7L73XnVQmbwgWKaJfkHbATfYOlU3iy5ne6/M7F0Jrgs7kYguu/wbspepeeC5GgeaV1Wwa9o5gTYdD/UOBk0WpR8HHUuNjxr6VUKRI5skORIFsvI4CB+GCMzZTLJQd18GkSjueW9xxRZ+Qju+jjmLYF3FveShX1KsxO+f9zQIXqj170/CQK8lA6NORn+HdY2/Uqq7tCZFvVjhWKtncGA4nnPQKeVsPOTMpYShz3AGBsKyat10CRSqpEbnAgXnzH4RnRrPCEGi/WhVHm1Mvllx1jTK2I3oUyC504fhIQogjrIzFvWleJ/L2/qyV56nWHpHefQiHUCSv3nc6Ry3URh1bwBTMvVOYhYsS/Crmpbd0BSs=
branches:
  only:
  - "/.*/"
