version: '3.7'
services:
   apt_fetch:
      restart: always
      image: aptrust/exchange_apt_volume_service:${DOCKER_TAG_NAME:-latest}
      volumes:
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}"
           target: /go/bin/data
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}/config"
           target: /go/bin/config
      env_file:
         - ".env"
   apt_file_delete:
      restart: always
      image: aptrust/exchange_apt_file_delete:${DOCKER_TAG_NAME:-latest}
      volumes:
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}"
           target: /go/bin/data
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}/config"
           target: /go/bin/config
      env_file:
         - ".env"
   apt_file_restore:
      restart: always
      image: aptrust/exchange_apt_file_restore:${DOCKER_TAG_NAME:-latest}
      volumes:
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}"
           target: /go/bin/data
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}/config"
           target: /go/bin/config
      env_file:
         - ".env"
   apt_fixity_check:
      restart: always
      image: aptrust/exchange_apt_fixity_check:${DOCKER_TAG_NAME:-latest}
      volumes:
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}"
           target: /go/bin/data
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}/config"
           target: /go/bin/config
      env_file:
         - ".env"
   apt_glacier_restore_init:
      restart: always
      image: aptrust/exchange_apt_glacier_restore_init:${DOCKER_TAG_NAME:-latest}
      volumes:
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}"
           target: /go/bin/data
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}/config"
           target: /go/bin/config
      env_file:
         - ".env"
   apt_record:
      restart: always
      image: aptrust/exchange_apt_record:${DOCKER_TAG_NAME:-latest}
      volumes:
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}"
           target: /go/bin/data
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}/config"
           target: /go/bin/config
      env_file:
         - ".env"
   apt_restore:
      restart: always
      image: aptrust/exchange_apt_restore:${DOCKER_TAG_NAME:-latest}
      volumes:
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}"
           target: /go/bin/data
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}/config"
           target: /go/bin/config
      env_file:
         - ".env"
   apt_store:
      restart: always
      image: aptrust/exchange_apt_store:${DOCKER_TAG_NAME:-latest}
      volumes:
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}"
           target: /go/bin/data
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}/config"
           target: /go/bin/config
      env_file:
         - ".env"
   apt_volume_service:
      restart: always
      image: aptrust/exchange_apt_volume_service:${DOCKER_TAG_NAME:-latest}
      volumes:
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}"
           target: /go/bin/data
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}/config"
           target: /go/bin/config
      env_file:
         - ".env"
   nsqlookupd:
      image: nsqio/nsq:v1.2.0
      hostname: nsqlookupd
      command: /nsqlookupd
      volumes:
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}/nsq"
           target: /data
      ports:
         - "4160:4160"
         - "4161:4161"
   nsqd:
      image: nsqio/nsq:v1.2.0
      command: /nsqd --lookupd-tcp-address=${nsq_lookupd_tcp_address} --data-path=/data --broadcast-address=${nsq_broadcast_address} --msg-timeout=${nsq_msg_timeout} --max-msg-timeout=${nsq_max_msg_timeout} --max-msg-size=${nsq_max_msg_size} -mem-queue-size=${nsq_mem_queue_size} -max-req-timeout=${nsq_max_req_timeout} -max-heartbeat-interval=${nsq_max_heartbeat_interval}
      volumes:
         - type: bind
           source: "${DOCKER_DATA_PATH:-./docker}/nsq"
           target: /data
      networks:
         default:
            aliases:
               - nsqd
               - "${nsq_broadcast_address}"
      restart: always
      depends_on:
         - nsqlookupd
      links:
         - nsqlookupd:nsqlookupd
      ports:
         - "4150:4150"
         - "4151:4151"
   nsqadmin:
      image: nsqio/nsq:v1.2.0
      command: /nsqadmin --lookupd-http-address=${nsq_lookupd_http_address}
      depends_on:
         - nsqlookupd
      links:
         - nsqlookupd:nsqlookupd
      ports:
         - "4171:4171"
      restart: always
networks:
   default:
