version: '3'
services:
   exchange_apt_fetch:
      restart: always
      image: registry.gitlab.com/aptrust/container-registry/exchange_apt_volume_service:${DOCKER_TAG_NAME:-latest}
      volumes:
         - ${DOCKER_DATA_PATH:./docker}:/go/bin/data
         - ${DOCKER_DATA_PATH:./docker}/exchange_apt_fetch:/go/bin/config
      env_file:
         - ".env"
   exchange_apt_file_delete:
      restart: always
      image: registry.gitlab.com/aptrust/container-registry/exchange_apt_file_delete:${DOCKER_TAG_NAME:-latest}
      volumes:
         - ${DOCKER_DATA_PATH:/docker}:/go/bin/data
         - ${DOCKER_DATA_PATH:/docker}/exchange_apt_file_delete:/go/bin/config
      env_file:
         - ".env"
   nsqlookupd:
      image: nsqio/nsq
      hostname: nsqlookupd
      command: /nsqlookupd
      volumes:
         - /srv/docker/nsqlookupd:/data
      ports:
        - "4160:4160"
        - "4161:4161"
   nsq:
      image: nsqio/nsq
      hostname: nsq
      command: /nsqd --broadcast-address nsq --lookupd-tcp-address=nsqlookupd:4160 --msg-timeout "60m0s" --max-msg-timeout "180m0s" --max-msg-size "31457280"
      volumes:
         - /srv/docker/nsqd:/data
      depends_on:
         - nsqlookupd
      links:
         - nsqlookupd:nsqlookupd
      ports:
         - "4150:4150"
         - "4151:4151"
      nsqadmin:
         image: nsqio/nsq
         hostname: nsqadmin
         command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
         volumes:
            - /srv/docker/nsqadmin:/data
         depends_on:
            - nsqlookupd
         links:
            - nsqlookupd:nsqlookupd
         ports:
            - "4171:4171"
